# -*- ii: apisnoop; -*-
#+TITLE: StorageV1 StorageClass Lifecycle Test
#+AUTHOR: ii team
#+TODO: TODO(t) NEXT(n) IN-PROGRESS(i) BLOCKED(b) | DONE(d)
#+OPTIONS: toc:nil tags:nil todo:nil
#+EXPORT_SELECT_TAGS: export
#+PROPERTY: header-args:sql-mode :product postgres


* TODO Progress [1/6]                                                :export:
- [ ] APISnoop org-flow : [[https://github.com/apisnoop/ticket-writing/blob/master/StorageV1StorageClass-LifecycleTest.org][StorageV1StorageClass-LifecycleTest.org]]
- [ ] test approval issue : [[https://issues.k8s.io/][#]]
- [ ] test pr : [[https://pr.k8s.io/][!]]
- [ ] two weeks soak start date : [[https://testgrid.k8s.io/][testgrid-link]]
- [ ] two weeks soak end date : xxxx-xx-xx
- [ ] test promotion pr : [[https://pr.k8s.io/][!]]

* Identifying an untested feature Using APISnoop                     :export:
** Untested Endpoints

According to following APIsnoop query, there are three StorageClass endpoints that are untested.

#+NAME: untested_stable_core_endpoints
#+begin_src sql-mode :eval never-export :exports both :session none
select   endpoint,
         path,
         kind
from     testing.untested_stable_endpoint
where    eligible is true
and      endpoint ilike '%StorageClass'
order by kind, endpoint
limit    10;
#+end_src

#+RESULTS: untested_stable_core_endpoints
#+begin_SRC example
               endpoint                |                     path                      |     kind
---------------------------------------+-----------------------------------------------+--------------
 deleteStorageV1CollectionStorageClass | /apis/storage.k8s.io/v1/storageclasses        | StorageClass
 patchStorageV1StorageClass            | /apis/storage.k8s.io/v1/storageclasses/{name} | StorageClass
 replaceStorageV1StorageClass          | /apis/storage.k8s.io/v1/storageclasses/{name} | StorageClass
(3 rows)

#+end_SRC

- https://apisnoop.cncf.io/1.27.0/stable/storage/deleteStorageV1CollectionStorageClass
- https://apisnoop.cncf.io/1.27.0/stable/storage/patchStorageV1StorageClass
- https://apisnoop.cncf.io/1.27.0/stable/storage/replaceStorageV1StorageClass

** Endpoints that are not Conformance tested

- https://apisnoop.cncf.io/1.27.0/stable/storage/createStorageV1StorageClass
- https://apisnoop.cncf.io/1.27.0/stable/storage/deleteStorageV1StorageClass
- https://apisnoop.cncf.io/1.27.0/stable/storage/listStorageV1StorageClass
- https://apisnoop.cncf.io/1.27.0/stable/storage/readStorageV1StorageClass

* API Reference and feature documentation                            :export:

- [[https://kubernetes.io/docs/reference/kubernetes-api/][Kubernetes API Reference Docs]]
- [[https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/][Kubernetes API / Config and Storage Resources / StorageClass]]
- [[https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/storage/v1/storageclass.go][client-go - StorageClass]]

* Test outline                                                       :export:

#+begin_src
Scenario: Test the lifecycle of a StorageClass
#+end_src

* E2E Test                                                           :export:

Using a number of existing e2e test practices a new [[https://github.com/ii/kubernetes][ginkgo test]] has been created to provide future Conformance coverage for the _ endpoints.
The e2e logs for this test are listed below.

#+begin_src

#+end_src

* Verifying increase in coverage with APISnoop                       :export:
** Listing endpoints hit by the new e2e test

This query shows the following StorageClass endpoints are hit within a short period of running this e2e test.

#+begin_src sql-mode :eval never-export :exports both :session none
select distinct substring(endpoint from '\w+') AS endpoint,
                right(useragent,50) AS useragent
from  testing.audit_event
where useragent like 'e2e%should%'
  and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 20000
  and endpoint ilike '%StorageClass%'
order by endpoint
limit 10;
#+end_src

* Final notes                                                        :export:

If a test with these calls gets merged, *test coverage will go up by _ points*

This test is also created with the goal of conformance promotion.

-----
/sig testing

/sig architecture

/area conformance
